### ISSUE TITLE
Рамки по ДСТУ

### ISSUE THREAD

**Issue by rostgw** [linevich/eskd-u#4]
Не могли бы Вы помочь с одной проблемой?
Недавно ознакомился с системой LaTeX, которая безусловно мне понравилась. Для вёрстки работ использовал пакет eskdx. С лабораторными работами проблем нет. Однако, для вёрстки курсовых, РГР, и других работ такого плана, мне нужно, чтобы в каждом новом разделе были заглавные рамки с своим отдельным шифром и надписью в ней. Можно ли это как-то реализовать?

**Comment by linevich** [comment]
Навряд чи чимось можу допомогти, давненько не працював з LaTeX та і цей "пакет" радше експеримент ніж щось реально готове до використання :)

Раджу звернутись в тематичну спільноту, там велетенська кількість матеріалів: https://tex.stackexchange.com/
